sudo: required
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
before_install:
  - curl https://coreos.com/dist/pubkeys/app-signing-pubkey.gpg | sudo apt-key add -
  - wget https://github.com/coreos/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -O /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
  - tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/test-etcd --strip-components=1
  - /tmp/test-etcd/etcd
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - cpanm --quiet --notest
  - cpanm --quiet --installdeps --notest .
  - cpan-install --coverage
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
env:
  - ETCD_VER=v3.1.5
  - ETCDCTL_API=3
  - ETCD_TEST_HOST=127.0.0.1
  - ETCD_TEST_PORT=2379
